/* GENERATED by scripts/gen-jni-registry.py — do not edit by hand.
 * Regenerate after adding, removing or changing a NativeBridge `external fun` or its C body;
 * CI runs the script with --check and fails if this file is stale. */
#ifndef DGB_JNI_REGISTRY_GEN_H
#define DGB_JNI_REGISTRY_GEN_H

#include <jni.h>
#include "jni_class_paths.h"

void JNICALL NativeBridge_addDandelionPeer(JNIEnv *env, jobject thiz, jstring ipStr);  /* jni_peer.c */
void JNICALL NativeBridge_addWatchedAddresses(JNIEnv *env, jobject thiz, jobjectArray addrs);  /* jni_wallet.c */
jbyteArray JNICALL NativeBridge_addressToScriptPubKey(JNIEnv *env, jobject thiz, jstring address);  /* jni_asset_send.c */
jlong JNICALL NativeBridge_backfillAbandonedBandStep(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jstring JNICALL NativeBridge_buildAndSignAssetTransferTx(JNIEnv *env, jobject thiz, jobjectArray inputTxidsHex, jintArray inputVouts, jlongArray inputAmounts, jobjectArray inputScriptPubKeysHex, jobjectArray outputAddresses, jlongArray outputAmounts, jobjectArray outputScriptsHex);  /* jni_asset_send.c */
jstring JNICALL NativeBridge_buildAndSignForeignAssetTransfer(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jstring hmacKey, jintArray prefixPath, jobjectArray txidsHex, jintArray vouts, jlongArray amounts, jintArray chainIndices, jintArray addressIndices, jobjectArray scriptPubKeysHex, jobjectArray outputAddresses, jlongArray outputAmounts, jobjectArray outputScriptsHex, jlong feePerKb);  /* jni_derive.c */
jstring JNICALL NativeBridge_buildAndSignForeignDigiDollarTransfer(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jobjectArray ddTxidsHex, jintArray ddVouts, jobjectArray ddScriptsHex, jintArray ddChains, jintArray ddIndices, jstring feeHmacKey, jintArray feePrefixPath, jobjectArray feeTxidsHex, jintArray feeVouts, jlongArray feeAmounts, jobjectArray feeScriptsHex, jintArray feeChains, jintArray feeIndices, jstring recipientKeyHex, jstring changeAddress, jlong changeAmount, jlong cents);  /* jni_derive.c */
jstring JNICALL NativeBridge_buildAndSignLegacySweep(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jstring hmacKey, jintArray prefixPath, jobjectArray txidsHex, jintArray vouts, jlongArray amounts, jintArray chainIndices, jintArray addressIndices, jobjectArray scriptPubKeysHex, jstring destAddress, jlong feePerKb);  /* jni_derive.c */
jint JNICALL NativeBridge_cfRecoveryDecide(JNIEnv *env, jobject thiz, jint reason);  /* jni_cf_recovery_policy.c */
jintArray JNICALL NativeBridge_classifyOutpoints(JNIEnv *env, jobject thiz, jobjectArray outpoints);  /* jni_wallet.c */
void JNICALL NativeBridge_clearPinnedPeer(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_clearSocksProxy(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_compactFilterPeerStatus(JNIEnv *env, jobject thiz, jstring ipStr, jint port);  /* jni_peer.c */
jboolean JNICALL NativeBridge_confirmTransaction(JNIEnv *env, jobject thiz, jstring txHashHex, jlong blockHeight, jlong blockTimestamp);  /* jni_transaction.c */
jbyteArray JNICALL NativeBridge_createTransaction(JNIEnv *env, jobject thiz, jstring toAddress, jlong amountSatoshis, jlong feePerKb);  /* jni_transaction.c */
jboolean JNICALL NativeBridge_createWalletFromBytes(JNIEnv *env, jobject thiz, jbyteArray phraseBytes, jbyteArray passphrase);  /* jni_wallet.c */
jobjectArray JNICALL NativeBridge_deriveAddresses(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jstring hmacKey, jintArray prefixPath, jint gapExternal, jint gapInternal, jint addressFormat);  /* jni_derive.c */
jobjectArray JNICALL NativeBridge_deriveDigiDollarAddresses(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jint gapExternal, jint gapInternal);  /* jni_derive.c */
jstring JNICALL NativeBridge_deriveIssuanceAssetId(JNIEnv *env, jobject thiz, jstring firstInputTxidHex, jint firstInputVout, jboolean locked, jint aggregation, jint divisibility);  /* jni_asset.c */
jstring JNICALL NativeBridge_derivePrivateKeyWIF(JNIEnv *env, jobject thiz, jbyteArray seedBytes, jstring hmacKey, jintArray fullPath);  /* jni_derive.c */
jlong JNICALL NativeBridge_digiDollarTxAmount(JNIEnv *env, jobject thiz, jstring txHashHex, jboolean isSend);  /* jni_transaction.c */
jint JNICALL NativeBridge_digiDollarTxType(JNIEnv *env, jobject thiz, jstring txHashHex);  /* jni_transaction.c */
void JNICALL NativeBridge_disableAutoCompactFilterFetch(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jstring JNICALL NativeBridge_dumpAllAddresses(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
void JNICALL NativeBridge_enableAutoCompactFilterFetch(JNIEnv *env, jobject thiz, jlong startHeight);  /* jni_peer.c */
void JNICALL NativeBridge_fluffTransaction(JNIEnv *env, jobject thiz, jstring jtxid);  /* jni_transaction.c */
void JNICALL NativeBridge_forceReconnect(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jstring JNICALL NativeBridge_generateMnemonic(JNIEnv *env, jobject thiz, jint entropyBits);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getAbandonedBelow(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getAbandonedCount(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getAbandonedHeightsTotal(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jobjectArray JNICALL NativeBridge_getAllTransactionHashes(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getAutoFetchCFiltersThrough(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getBalance(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jint JNICALL NativeBridge_getCFChainTipHeight(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getCFCheckptDisagreeCount(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getCFCorroboratedThrough(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlongArray JNICALL NativeBridge_getCfScanLedgerCounts(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlongArray JNICALL NativeBridge_getCfScanLedgerHoleRanges(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jstring JNICALL NativeBridge_getChangeAddress(JNIEnv *env, jobject thiz, jint index, jint format);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getCheckpointTimeAtOrBelow(JNIEnv *env, jobject thiz, jlong height);  /* jni_peer.c */
jbyteArray JNICALL NativeBridge_getCompactFilterChain(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getConvoyAbandonmentPending(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getConvoyRearmMax(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getConvoyWindow(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jstring JNICALL NativeBridge_getDerivationPath(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getDigiDollarBalance(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jstring JNICALL NativeBridge_getDigiDollarReceiveAddress(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jstring JNICALL NativeBridge_getDigiDollarTaprootKeyHex(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getEstimatedBlockHeight(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getEstimatedFee(JNIEnv *env, jobject thiz, jint priority);  /* jni_transaction.c */
jstring JNICALL NativeBridge_getFilterElementStats(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jlong JNICALL NativeBridge_getLastBlockHeight(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getLowestNeededHeight(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jbyteArray JNICALL NativeBridge_getOpReturnData(JNIEnv *env, jobject thiz, jbyteArray rawTx);  /* jni_asset.c */
jint JNICALL NativeBridge_getPeerCount(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getPublishResult(JNIEnv *env, jobject thiz, jstring txidHex);  /* jni_transaction.c */
jobjectArray JNICALL NativeBridge_getRawTransactionInputs(JNIEnv *env, jobject thiz, jbyteArray rawTx);  /* jni_asset.c */
jobjectArray JNICALL NativeBridge_getRawTransactionOutputs(JNIEnv *env, jobject thiz, jbyteArray rawTx);  /* jni_asset.c */
jstring JNICALL NativeBridge_getReceiveAddress(JNIEnv *env, jobject thiz, jint index, jint format);  /* jni_wallet.c */
jint JNICALL NativeBridge_getRelayCount(JNIEnv *env, jobject thiz, jstring jtxid);  /* jni_transaction.c */
jlong JNICALL NativeBridge_getSavedBlocksTip(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlong JNICALL NativeBridge_getScanLedgerStart(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jbyteArray JNICALL NativeBridge_getSerializedTransactionForHash(JNIEnv *env, jobject thiz, jstring txHashHex);  /* jni_asset.c */
jbyteArray JNICALL NativeBridge_getSerializedTransactions(JNIEnv *env, jobject thiz);  /* jni_transaction_persist.c */
jstring JNICALL NativeBridge_getSpendableDigiByteUtxos(JNIEnv *env, jobject thiz);  /* jni_asset_send.c */
jint JNICALL NativeBridge_getSyncMode(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_getTransactionCount(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jstring JNICALL NativeBridge_getTransactionDetails(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
jobjectArray JNICALL NativeBridge_getTransactionInputsForHash(JNIEnv *env, jobject thiz, jstring txHashHex);  /* jni_asset.c */
jobjectArray JNICALL NativeBridge_getTransactionOutputsForHash(JNIEnv *env, jobject thiz, jstring txHashHex);  /* jni_asset.c */
jlong JNICALL NativeBridge_getWalletBirthCheckpointHeight(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_hasDandelionPeer(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_hasLegacyFunds(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
void JNICALL NativeBridge_injectPeerByIp(JNIEnv *env, jobject thiz, jstring ipStr, jint port, jlong servicesHex);  /* jni_peer.c */
jboolean JNICALL NativeBridge_isAssetTransaction(JNIEnv *env, jobject thiz, jbyteArray rawTx);  /* jni_asset.c */
jboolean JNICALL NativeBridge_isRawTransactionSigned(JNIEnv *env, jobject thiz, jstring rawTxHex);  /* jni_derive.c */
jboolean JNICALL NativeBridge_isStatusStale(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_isTransactionValid(JNIEnv *env, jobject thiz, jstring jtxid);  /* jni_transaction.c */
jboolean JNICALL NativeBridge_isValidAddress(JNIEnv *env, jobject thiz, jstring address);  /* jni_wallet.c */
jboolean JNICALL NativeBridge_isValidDigiDollarAddress(JNIEnv *env, jobject thiz, jstring addr);  /* jni_transaction.c */
jboolean JNICALL NativeBridge_isValidMnemonic(JNIEnv *env, jobject thiz, jstring phrase);  /* jni_wallet.c */
jboolean JNICALL NativeBridge_isWalletLoaded(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
void JNICALL NativeBridge_keepAlivePeers(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jint JNICALL NativeBridge_loadPeerPenalties(JNIEnv *env, jobject thiz, jbyteArray blob);  /* jni_peer.c */
jint JNICALL NativeBridge_loadSavedBlocks(JNIEnv *env, jobject thiz, jbyteArray data);  /* jni_peer.c */
jint JNICALL NativeBridge_loadSavedPeers(JNIEnv *env, jobject thiz, jbyteArray data);  /* jni_peer.c */
jint JNICALL NativeBridge_loadSerializedTransactions(JNIEnv *env, jobject thiz, jbyteArray data);  /* jni_transaction_persist.c */
jstring JNICALL NativeBridge_lockHolderInfo(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_lockSession(JNIEnv *env, jobject thiz);  /* jni_wallet.c */
void JNICALL NativeBridge_markInitialSyncDone(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_markSavedBlocksLoadComplete(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jbyteArray JNICALL NativeBridge_mnemonicToSeed(JNIEnv *env, jobject thiz, jbyteArray phraseBytes, jbyteArray passphrase);  /* jni_derive.c */
jint JNICALL NativeBridge_outpointSpentState(JNIEnv *env, jobject thiz, jstring txHashHex, jint vout);  /* jni_wallet.c */
jint JNICALL NativeBridge_peerPenaltyDecide(JNIEnv *env, jobject thiz, jbyteArray blob);  /* jni_peer_penalty_persist.c */
jint JNICALL NativeBridge_peerPenaltyDecideLength(JNIEnv *env, jobject thiz, jint length);  /* jni_peer_penalty_persist.c */
jint JNICALL NativeBridge_peerPenaltyEntryBytes(JNIEnv *env, jobject thiz);  /* jni_peer_penalty_persist.c */
jint JNICALL NativeBridge_peerPenaltyHeaderBytes(JNIEnv *env, jobject thiz);  /* jni_peer_penalty_persist.c */
jint JNICALL NativeBridge_publishErrnoValue(JNIEnv *env, jobject thiz, jint index);  /* jni_publish_outcome.c */
jint JNICALL NativeBridge_publishOutcomeOf(JNIEnv *env, jobject thiz, jint error);  /* jni_publish_outcome.c */
jstring JNICALL NativeBridge_publishTransaction(JNIEnv *env, jobject thiz, jbyteArray signedTx);  /* jni_transaction.c */
jstring JNICALL NativeBridge_publishTransactionStem(JNIEnv *env, jobject thiz, jbyteArray signedTx);  /* jni_transaction.c */
jstring JNICALL NativeBridge_rawTransactionId(JNIEnv *env, jobject thiz, jbyteArray rawTx);  /* jni_asset_send.c */
jboolean JNICALL NativeBridge_reanchorCompactFilterChainAtFloor(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_recoverWalletFromBytes(JNIEnv *env, jobject thiz, jbyteArray phraseBytes, jlong creationTimestamp, jbyteArray passphrase);  /* jni_wallet.c */
jboolean JNICALL NativeBridge_recreateContinuesAfterFailure(JNIEnv *env, jobject thiz, jint step);  /* jni_recreate_sequence.c */
jint JNICALL NativeBridge_recreateStepAt(JNIEnv *env, jobject thiz, jint index);  /* jni_recreate_sequence.c */
jint JNICALL NativeBridge_recreateStepCount(JNIEnv *env, jobject thiz);  /* jni_recreate_sequence.c */
jstring JNICALL NativeBridge_recreateStepName(JNIEnv *env, jobject thiz, jint step);  /* jni_recreate_sequence.c */
jboolean JNICALL NativeBridge_registerAssetOutpoint(JNIEnv *env, jobject thiz, jstring txHashHex, jint vout);  /* jni_wallet.c */
jboolean JNICALL NativeBridge_registerRawTransaction(JNIEnv *env, jobject thiz, jbyteArray rawTx, jlong blockHeight, jlong blockTimestamp);  /* jni_transaction.c */
jboolean JNICALL NativeBridge_removeTransaction(JNIEnv *env, jobject thiz, jstring jtxid);  /* jni_transaction.c */
jlong JNICALL NativeBridge_requestCompactFilters(JNIEnv *env, jobject thiz, jlong startHeight, jlong stopHeight);  /* jni_peer.c */
jint JNICALL NativeBridge_rerequestHeadersFromTip(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_rescan(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_restoreCfScanLedger(JNIEnv *env, jobject thiz, jbyteArray data);  /* jni_peer.c */
jstring JNICALL NativeBridge_sendDigiDollar(JNIEnv *env, jobject thiz, jstring tdAddress, jlong cents);  /* jni_transaction.c */
jbyteArray JNICALL NativeBridge_serializePeerPenalties(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_setCallbackHandler(JNIEnv *env, jobject thiz, jobject handler);  /* jni_peer.c */
jboolean JNICALL NativeBridge_setCompactFilterChain(JNIEnv *env, jobject thiz, jbyteArray data);  /* jni_peer.c */
void JNICALL NativeBridge_setDandelionEnabled(JNIEnv *env, jobject thiz, jboolean enabled);  /* jni_peer.c */
void JNICALL NativeBridge_setMaxPeerConnections(JNIEnv *env, jobject thiz, jint count);  /* jni_peer.c */
void JNICALL NativeBridge_setNetwork(JNIEnv *env, jobject thiz, jboolean isTestnet);  /* jni_wallet.c */
void JNICALL NativeBridge_setPinnedPeer(JNIEnv *env, jobject thiz, jstring ipStr, jint port, jboolean exclusive);  /* jni_peer.c */
void JNICALL NativeBridge_setSocksProxy(JNIEnv *env, jobject thiz, jstring host, jint port);  /* jni_peer.c */
void JNICALL NativeBridge_setSyncMode(JNIEnv *env, jobject thiz, jint mode);  /* jni_peer.c */
jstring JNICALL NativeBridge_signIdentityMessage(JNIEnv *env, jobject thiz, jstring message, jstring siteUri, jint index);  /* jni_wallet_sign.c */
jstring JNICALL NativeBridge_signMessage(JNIEnv *env, jobject thiz, jstring message, jint addressFormat);  /* jni_wallet_sign.c */
jbyteArray JNICALL NativeBridge_signTransaction(JNIEnv *env, jobject thiz, jbyteArray unsignedTx);  /* jni_transaction.c */
jlong JNICALL NativeBridge_snapAutoFetchThroughToScanFrontier(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jlongArray JNICALL NativeBridge_spendableNotListed(JNIEnv *env, jobject thiz, jobjectArray outpoints);  /* jni_wallet.c */
void JNICALL NativeBridge_startSync(JNIEnv *env, jobject thiz);  /* jni_peer.c */
void JNICALL NativeBridge_stopSync(JNIEnv *env, jobject thiz);  /* jni_peer.c */
jboolean JNICALL NativeBridge_walletContainsAddress(JNIEnv *env, jobject thiz, jstring address);  /* jni_wallet.c */

#define DGB_JNI_NATIVEBRIDGE_METHODS \
    { "addDandelionPeer", "(Ljava/lang/String;)V", (void *) NativeBridge_addDandelionPeer }, \
    { "addWatchedAddresses", "([Ljava/lang/String;)V", (void *) NativeBridge_addWatchedAddresses }, \
    { "addressToScriptPubKey", "(Ljava/lang/String;)[B", (void *) NativeBridge_addressToScriptPubKey }, \
    { "backfillAbandonedBandStep", "()J", (void *) NativeBridge_backfillAbandonedBandStep }, \
    { "buildAndSignAssetTransferTx", "([Ljava/lang/String;[I[J[Ljava/lang/String;[Ljava/lang/String;[J[Ljava/lang/String;)Ljava/lang/String;", (void *) NativeBridge_buildAndSignAssetTransferTx }, \
    { "buildAndSignForeignAssetTransfer", "([BLjava/lang/String;[I[Ljava/lang/String;[I[J[I[I[Ljava/lang/String;[Ljava/lang/String;[J[Ljava/lang/String;J)Ljava/lang/String;", (void *) NativeBridge_buildAndSignForeignAssetTransfer }, \
    { "buildAndSignForeignDigiDollarTransfer", "([B[Ljava/lang/String;[I[Ljava/lang/String;[I[ILjava/lang/String;[I[Ljava/lang/String;[I[J[Ljava/lang/String;[I[ILjava/lang/String;Ljava/lang/String;JJ)Ljava/lang/String;", (void *) NativeBridge_buildAndSignForeignDigiDollarTransfer }, \
    { "buildAndSignLegacySweep", "([BLjava/lang/String;[I[Ljava/lang/String;[I[J[I[I[Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;", (void *) NativeBridge_buildAndSignLegacySweep }, \
    { "cfRecoveryDecide", "(I)I", (void *) NativeBridge_cfRecoveryDecide }, \
    { "classifyOutpoints", "([Ljava/lang/String;)[I", (void *) NativeBridge_classifyOutpoints }, \
    { "clearPinnedPeer", "()V", (void *) NativeBridge_clearPinnedPeer }, \
    { "clearSocksProxy", "()V", (void *) NativeBridge_clearSocksProxy }, \
    { "compactFilterPeerStatus", "(Ljava/lang/String;I)I", (void *) NativeBridge_compactFilterPeerStatus }, \
    { "confirmTransaction", "(Ljava/lang/String;JJ)Z", (void *) NativeBridge_confirmTransaction }, \
    { "createTransaction", "(Ljava/lang/String;JJ)[B", (void *) NativeBridge_createTransaction }, \
    { "createWalletFromBytes", "([B[B)Z", (void *) NativeBridge_createWalletFromBytes }, \
    { "deriveAddresses", "([BLjava/lang/String;[IIII)[Ljava/lang/String;", (void *) NativeBridge_deriveAddresses }, \
    { "deriveDigiDollarAddresses", "([BII)[Ljava/lang/String;", (void *) NativeBridge_deriveDigiDollarAddresses }, \
    { "deriveIssuanceAssetId", "(Ljava/lang/String;IZII)Ljava/lang/String;", (void *) NativeBridge_deriveIssuanceAssetId }, \
    { "derivePrivateKeyWIF", "([BLjava/lang/String;[I)Ljava/lang/String;", (void *) NativeBridge_derivePrivateKeyWIF }, \
    { "digiDollarTxAmount", "(Ljava/lang/String;Z)J", (void *) NativeBridge_digiDollarTxAmount }, \
    { "digiDollarTxType", "(Ljava/lang/String;)I", (void *) NativeBridge_digiDollarTxType }, \
    { "disableAutoCompactFilterFetch", "()V", (void *) NativeBridge_disableAutoCompactFilterFetch }, \
    { "dumpAllAddresses", "()Ljava/lang/String;", (void *) NativeBridge_dumpAllAddresses }, \
    { "enableAutoCompactFilterFetch", "(J)V", (void *) NativeBridge_enableAutoCompactFilterFetch }, \
    { "fluffTransaction", "(Ljava/lang/String;)V", (void *) NativeBridge_fluffTransaction }, \
    { "forceReconnect", "()V", (void *) NativeBridge_forceReconnect }, \
    { "generateMnemonic", "(I)Ljava/lang/String;", (void *) NativeBridge_generateMnemonic }, \
    { "getAbandonedBelow", "()J", (void *) NativeBridge_getAbandonedBelow }, \
    { "getAbandonedCount", "()J", (void *) NativeBridge_getAbandonedCount }, \
    { "getAbandonedHeightsTotal", "()J", (void *) NativeBridge_getAbandonedHeightsTotal }, \
    { "getAllTransactionHashes", "()[Ljava/lang/String;", (void *) NativeBridge_getAllTransactionHashes }, \
    { "getAutoFetchCFiltersThrough", "()J", (void *) NativeBridge_getAutoFetchCFiltersThrough }, \
    { "getBalance", "()J", (void *) NativeBridge_getBalance }, \
    { "getCFChainTipHeight", "()I", (void *) NativeBridge_getCFChainTipHeight }, \
    { "getCFCheckptDisagreeCount", "()I", (void *) NativeBridge_getCFCheckptDisagreeCount }, \
    { "getCFCorroboratedThrough", "()I", (void *) NativeBridge_getCFCorroboratedThrough }, \
    { "getCfScanLedgerCounts", "()[J", (void *) NativeBridge_getCfScanLedgerCounts }, \
    { "getCfScanLedgerHoleRanges", "()[J", (void *) NativeBridge_getCfScanLedgerHoleRanges }, \
    { "getChangeAddress", "(II)Ljava/lang/String;", (void *) NativeBridge_getChangeAddress }, \
    { "getCheckpointTimeAtOrBelow", "(J)J", (void *) NativeBridge_getCheckpointTimeAtOrBelow }, \
    { "getCompactFilterChain", "()[B", (void *) NativeBridge_getCompactFilterChain }, \
    { "getConvoyAbandonmentPending", "()I", (void *) NativeBridge_getConvoyAbandonmentPending }, \
    { "getConvoyRearmMax", "()I", (void *) NativeBridge_getConvoyRearmMax }, \
    { "getConvoyWindow", "()I", (void *) NativeBridge_getConvoyWindow }, \
    { "getDerivationPath", "()Ljava/lang/String;", (void *) NativeBridge_getDerivationPath }, \
    { "getDigiDollarBalance", "()J", (void *) NativeBridge_getDigiDollarBalance }, \
    { "getDigiDollarReceiveAddress", "()Ljava/lang/String;", (void *) NativeBridge_getDigiDollarReceiveAddress }, \
    { "getDigiDollarTaprootKeyHex", "()Ljava/lang/String;", (void *) NativeBridge_getDigiDollarTaprootKeyHex }, \
    { "getEstimatedBlockHeight", "()J", (void *) NativeBridge_getEstimatedBlockHeight }, \
    { "getEstimatedFee", "(I)J", (void *) NativeBridge_getEstimatedFee }, \
    { "getFilterElementStats", "()Ljava/lang/String;", (void *) NativeBridge_getFilterElementStats }, \
    { "getLastBlockHeight", "()J", (void *) NativeBridge_getLastBlockHeight }, \
    { "getLowestNeededHeight", "()J", (void *) NativeBridge_getLowestNeededHeight }, \
    { "getOpReturnData", "([B)[B", (void *) NativeBridge_getOpReturnData }, \
    { "getPeerCount", "()I", (void *) NativeBridge_getPeerCount }, \
    { "getPublishResult", "(Ljava/lang/String;)I", (void *) NativeBridge_getPublishResult }, \
    { "getRawTransactionInputs", "([B)[Ljava/lang/String;", (void *) NativeBridge_getRawTransactionInputs }, \
    { "getRawTransactionOutputs", "([B)[Ljava/lang/String;", (void *) NativeBridge_getRawTransactionOutputs }, \
    { "getReceiveAddress", "(II)Ljava/lang/String;", (void *) NativeBridge_getReceiveAddress }, \
    { "getRelayCount", "(Ljava/lang/String;)I", (void *) NativeBridge_getRelayCount }, \
    { "getSavedBlocksTip", "()J", (void *) NativeBridge_getSavedBlocksTip }, \
    { "getScanLedgerStart", "()J", (void *) NativeBridge_getScanLedgerStart }, \
    { "getSerializedTransactionForHash", "(Ljava/lang/String;)[B", (void *) NativeBridge_getSerializedTransactionForHash }, \
    { "getSerializedTransactions", "()[B", (void *) NativeBridge_getSerializedTransactions }, \
    { "getSpendableDigiByteUtxos", "()Ljava/lang/String;", (void *) NativeBridge_getSpendableDigiByteUtxos }, \
    { "getSyncMode", "()I", (void *) NativeBridge_getSyncMode }, \
    { "getTransactionCount", "()I", (void *) NativeBridge_getTransactionCount }, \
    { "getTransactionDetails", "()Ljava/lang/String;", (void *) NativeBridge_getTransactionDetails }, \
    { "getTransactionInputsForHash", "(Ljava/lang/String;)[Ljava/lang/String;", (void *) NativeBridge_getTransactionInputsForHash }, \
    { "getTransactionOutputsForHash", "(Ljava/lang/String;)[Ljava/lang/String;", (void *) NativeBridge_getTransactionOutputsForHash }, \
    { "getWalletBirthCheckpointHeight", "()J", (void *) NativeBridge_getWalletBirthCheckpointHeight }, \
    { "hasDandelionPeer", "()Z", (void *) NativeBridge_hasDandelionPeer }, \
    { "hasLegacyFunds", "()Z", (void *) NativeBridge_hasLegacyFunds }, \
    { "injectPeerByIp", "(Ljava/lang/String;IJ)V", (void *) NativeBridge_injectPeerByIp }, \
    { "isAssetTransaction", "([B)Z", (void *) NativeBridge_isAssetTransaction }, \
    { "isRawTransactionSigned", "(Ljava/lang/String;)Z", (void *) NativeBridge_isRawTransactionSigned }, \
    { "isStatusStale", "()Z", (void *) NativeBridge_isStatusStale }, \
    { "isTransactionValid", "(Ljava/lang/String;)Z", (void *) NativeBridge_isTransactionValid }, \
    { "isValidAddress", "(Ljava/lang/String;)Z", (void *) NativeBridge_isValidAddress }, \
    { "isValidDigiDollarAddress", "(Ljava/lang/String;)Z", (void *) NativeBridge_isValidDigiDollarAddress }, \
    { "isValidMnemonic", "(Ljava/lang/String;)Z", (void *) NativeBridge_isValidMnemonic }, \
    { "isWalletLoaded", "()Z", (void *) NativeBridge_isWalletLoaded }, \
    { "keepAlivePeers", "()V", (void *) NativeBridge_keepAlivePeers }, \
    { "loadPeerPenalties", "([B)I", (void *) NativeBridge_loadPeerPenalties }, \
    { "loadSavedBlocks", "([B)I", (void *) NativeBridge_loadSavedBlocks }, \
    { "loadSavedPeers", "([B)I", (void *) NativeBridge_loadSavedPeers }, \
    { "loadSerializedTransactions", "([B)I", (void *) NativeBridge_loadSerializedTransactions }, \
    { "lockHolderInfo", "()Ljava/lang/String;", (void *) NativeBridge_lockHolderInfo }, \
    { "lockSession", "()V", (void *) NativeBridge_lockSession }, \
    { "markInitialSyncDone", "()V", (void *) NativeBridge_markInitialSyncDone }, \
    { "markSavedBlocksLoadComplete", "()V", (void *) NativeBridge_markSavedBlocksLoadComplete }, \
    { "mnemonicToSeed", "([B[B)[B", (void *) NativeBridge_mnemonicToSeed }, \
    { "outpointSpentState", "(Ljava/lang/String;I)I", (void *) NativeBridge_outpointSpentState }, \
    { "peerPenaltyDecide", "([B)I", (void *) NativeBridge_peerPenaltyDecide }, \
    { "peerPenaltyDecideLength", "(I)I", (void *) NativeBridge_peerPenaltyDecideLength }, \
    { "peerPenaltyEntryBytes", "()I", (void *) NativeBridge_peerPenaltyEntryBytes }, \
    { "peerPenaltyHeaderBytes", "()I", (void *) NativeBridge_peerPenaltyHeaderBytes }, \
    { "publishErrnoValue", "(I)I", (void *) NativeBridge_publishErrnoValue }, \
    { "publishOutcomeOf", "(I)I", (void *) NativeBridge_publishOutcomeOf }, \
    { "publishTransaction", "([B)Ljava/lang/String;", (void *) NativeBridge_publishTransaction }, \
    { "publishTransactionStem", "([B)Ljava/lang/String;", (void *) NativeBridge_publishTransactionStem }, \
    { "rawTransactionId", "([B)Ljava/lang/String;", (void *) NativeBridge_rawTransactionId }, \
    { "reanchorCompactFilterChainAtFloor", "()Z", (void *) NativeBridge_reanchorCompactFilterChainAtFloor }, \
    { "recoverWalletFromBytes", "([BJ[B)Z", (void *) NativeBridge_recoverWalletFromBytes }, \
    { "recreateContinuesAfterFailure", "(I)Z", (void *) NativeBridge_recreateContinuesAfterFailure }, \
    { "recreateStepAt", "(I)I", (void *) NativeBridge_recreateStepAt }, \
    { "recreateStepCount", "()I", (void *) NativeBridge_recreateStepCount }, \
    { "recreateStepName", "(I)Ljava/lang/String;", (void *) NativeBridge_recreateStepName }, \
    { "registerAssetOutpoint", "(Ljava/lang/String;I)Z", (void *) NativeBridge_registerAssetOutpoint }, \
    { "registerRawTransaction", "([BJJ)Z", (void *) NativeBridge_registerRawTransaction }, \
    { "removeTransaction", "(Ljava/lang/String;)Z", (void *) NativeBridge_removeTransaction }, \
    { "requestCompactFilters", "(JJ)J", (void *) NativeBridge_requestCompactFilters }, \
    { "rerequestHeadersFromTip", "()I", (void *) NativeBridge_rerequestHeadersFromTip }, \
    { "rescan", "()V", (void *) NativeBridge_rescan }, \
    { "restoreCfScanLedger", "([B)Z", (void *) NativeBridge_restoreCfScanLedger }, \
    { "sendDigiDollar", "(Ljava/lang/String;J)Ljava/lang/String;", (void *) NativeBridge_sendDigiDollar }, \
    { "serializePeerPenalties", "()[B", (void *) NativeBridge_serializePeerPenalties }, \
    { "setCallbackHandler", "(" DGB_JNI_NATIVECALLBACK_SIG ")V", (void *) NativeBridge_setCallbackHandler }, \
    { "setCompactFilterChain", "([B)Z", (void *) NativeBridge_setCompactFilterChain }, \
    { "setDandelionEnabled", "(Z)V", (void *) NativeBridge_setDandelionEnabled }, \
    { "setMaxPeerConnections", "(I)V", (void *) NativeBridge_setMaxPeerConnections }, \
    { "setNetwork", "(Z)V", (void *) NativeBridge_setNetwork }, \
    { "setPinnedPeer", "(Ljava/lang/String;IZ)V", (void *) NativeBridge_setPinnedPeer }, \
    { "setSocksProxy", "(Ljava/lang/String;I)V", (void *) NativeBridge_setSocksProxy }, \
    { "setSyncMode", "(I)V", (void *) NativeBridge_setSyncMode }, \
    { "signIdentityMessage", "(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;", (void *) NativeBridge_signIdentityMessage }, \
    { "signMessage", "(Ljava/lang/String;I)Ljava/lang/String;", (void *) NativeBridge_signMessage }, \
    { "signTransaction", "([B)[B", (void *) NativeBridge_signTransaction }, \
    { "snapAutoFetchThroughToScanFrontier", "()J", (void *) NativeBridge_snapAutoFetchThroughToScanFrontier }, \
    { "spendableNotListed", "([Ljava/lang/String;)[J", (void *) NativeBridge_spendableNotListed }, \
    { "startSync", "()V", (void *) NativeBridge_startSync }, \
    { "stopSync", "()V", (void *) NativeBridge_stopSync }, \
    { "walletContainsAddress", "(Ljava/lang/String;)Z", (void *) NativeBridge_walletContainsAddress }, \

#define DGB_JNI_NATIVEBRIDGE_METHOD_COUNT 134

#endif
