#!/usr/bin/env python3
"""Write checkpoint_diff_context_vectors.inc for checkpoint_diff_context_kat.

The fixture is bound to one mainnet checkpoint that carries a difficulty context in BRChainParams.h (default: the
newest checkpoint in the table). It holds:
  - real consecutive headers directly above that checkpoint, from the local full node (read-only RPC), each linked
    to the row before it and the first linked to the checkpoint's own header (the last row of its context);
  - two headers at the easiest target the wallet accepts (0x1e0fffff), proof of work ground to meet it: one on the
    checkpoint itself, one on the 30th real header above it.
The independent MultiShield V4 reference in ../header_diff_v4_kat/gen_vectors.py is run over the SHIPPED context rows
(read from BRChainParams.h, not from the node) followed by the real headers. The file is written only if the reference
judges every real header (none skipped) and agrees with its nBits, and only if it expects a different target for each
easiest-target header.

    gen_vectors.py [checkpoint_height]
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.dont_write_bytecode = True   # no __pycache__ in the sibling suite's directory
sys.path.insert(0, os.path.join(HERE, "..", "header_diff_v4_kat"))
from gen_vectors import MAIN_CLI, check_linked, dsha, fetch_rpc, grind_easiest, parse, rpc, set_compact, v4, algo_of  # noqa: E402

CORE = os.path.join(HERE, "..", "..", "..", "main", "jni", "digibytewallet-core")
ABOVE = 150          # real headers above the checkpoint
SECOND_ON = 30       # the second easiest-target header sits on this many real headers above the checkpoint


def shipped_context(src, height):
    m = re.search(r"BRMainNetCheckpointContext%d\[\]\s*=\s*\{(.*?)\n\};" % height, src, re.S)
    if not m:
        sys.exit("BRChainParams.h carries no difficulty context for checkpoint %d" % height)
    hexes = re.findall(r'"([0-9a-f]{160})"', m.group(1))
    return [parse(bytes.fromhex(h), height - len(hexes) + 1 + i) for i, h in enumerate(hexes)]


def main():
    src = open(os.path.join(CORE, "BRChainParams.h")).read()
    table = re.search(r"BRMainNetCheckpoints\[\]\s*=\s*\{(.*?)\n\};", src, re.S).group(1)
    cps = {int(h): (hsh, int(t), int(b, 16)) for h, hsh, t, b in re.findall(
        r'\{\s*(\d+),\s*uint256\("([0-9a-f]{64})"\),\s*(\d+),\s*(0x[0-9a-f]+)\s*\}', table)}
    cp = int(sys.argv[1]) if len(sys.argv) > 1 else max(cps)
    ctx = shipped_context(src, cp)
    check_linked(ctx)
    assert dsha(ctx[-1]["raw"])[::-1].hex() == cps[cp][0], "context does not end at the checkpoint"

    node = "mainnet node " + json.loads(rpc(MAIN_CLI, "getnetworkinfo"))["subversion"]
    above = fetch_rpc(MAIN_CLI, cp + 1, ABOVE)
    rows = ctx + above
    check_linked(rows)

    judged = 0
    for i in range(len(ctx), len(rows)):
        e = v4(rows, i, "main")
        if e is None:
            sys.exit("reference cannot judge height %d from the shipped context" % rows[i]["height"])
        if e != rows[i]["bits"]:
            sys.exit("REFERENCE DISAGREES at height %d: bits %08x, V4 %08x" % (rows[i]["height"], rows[i]["bits"], e))
        judged += 1

    easy = []
    for k in (len(ctx) - 1, len(ctx) - 1 + SECOND_ON):   # parent row: the checkpoint, then the 30th real header
        hdr, nonce = grind_easiest(rows[k])
        assert int.from_bytes(dsha(hdr), "little") <= set_compact(0x1E0FFFFF)
        expected = v4(rows[:k + 1] + [parse(hdr, rows[k]["height"] + 1)], k + 1, "main")
        assert expected is not None and expected != 0x1E0FFFFF
        easy.append((hdr, nonce, rows[k]["height"] + 1, expected))
        print("easiest-target header at %d: nonce %d, V4 expects %08x" % (rows[k]["height"] + 1, nonce, expected))

    with open(os.path.join(HERE, "checkpoint_diff_context_vectors.inc"), "w") as f:
        f.write("// AUTO-GENERATED by gen_vectors.py -- DO NOT HAND-EDIT. Regenerate instead.\n")
        f.write("// Checkpoint %d (it must carry a difficulty context in BRChainParams.h). Real headers above it from\n" % cp)
        f.write("// %s, linked to its context's last row. The independent V4 reference over the SHIPPED context\n" % node)
        f.write("// plus these rows judges all %d and agrees with every nBits.\n\n" % judged)
        f.write("static const uint32_t kCheckpointHeight = %d;\n" % cp)
        f.write("static const char *const kAbove[%d] = {\n" % len(above))
        for r in above:
            f.write('    "%s", // %d %s\n' % (r["raw"].hex(), r["height"], algo_of(r["version"]) or "unknown"))
        f.write("};\n")
        f.write("static const uint32_t kAboveJudged = %d;\n\n" % judged)
        f.write("// sha256d headers at the easiest target the wallet accepts (0x1e0fffff), proof of work met; the first on\n")
        f.write("// the checkpoint, the second on kAbove[%d]. kEasyExpected: the target V4 gives each from the real chain.\n" % (SECOND_ON - 1))
        f.write("static const uint32_t kSecondOn = %d;\n" % SECOND_ON)
        f.write("static const char *const kEasy[2] = {\n")
        for hdr, nonce, h, _ in easy:
            f.write('    "%s", // %d nonce %d\n' % (hdr.hex(), h, nonce))
        f.write("};\n")
        f.write("static const uint32_t kEasyExpected[2] = { 0x%08x, 0x%08x };\n" % (easy[0][3], easy[1][3]))
    print("wrote checkpoint %d: %d real headers (all judged), 2 easiest-target headers" % (cp, judged))


if __name__ == "__main__":
    main()
