#!/usr/bin/env python3
"""Write cf_checkpoint_fold_vectors.h — the chain data cf_checkpoint_fold_kat folds.

For every height pinned in BRCompactFilterCheckpoints.h this records the two inputs
BIP157 defines a filter header from: the block's filter hash, and the filter header of
the block before it. The KAT folds them with the wallet's own code and requires the
result to equal the pinned row.

Run it against a node OTHER than the one the table was generated from, so the table
and its proof do not share a source:

    gen_vectors.py                                   # local digibyte-cli
    gen_vectors.py ssh -i KEY root@HOST /usr/local/bin/digibyte-cli

The node needs blockfilterindex=1. Nothing here writes to the table.
"""
import hashlib, json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
CORE = os.path.normpath(os.path.join(HERE, "../../../main/jni/digibytewallet-core"))
CLI = sys.argv[1:] or ["/usr/local/bin/digibyte-cli"]


def rpc(*args):
    return subprocess.check_output([*CLI, *args], text=True).strip()


def dsha(b):
    return hashlib.sha256(hashlib.sha256(b).digest()).digest()


table = open(os.path.join(CORE, "BRCompactFilterCheckpoints.h")).read()
heights = [int(h) for h in re.findall(r'\{\s*(\d+),\s*uint256\("[0-9a-fA-F]{64}"\)\s*\}', table)]
if not heights:
    sys.exit("no rows found in BRCompactFilterCheckpoints.h")

out = os.path.join(HERE, "cf_checkpoint_fold_vectors.h")
with open(out, "w") as f:
    f.write("// AUTO-GENERATED by gen_vectors.py — DO NOT HAND-EDIT.\n")
    f.write("// One entry per pinned height: { height, filter header of height-1, filter hash of\n")
    f.write("// height }, both in the wallet's internal byte order. %d entries, newest %d.\n"
            % (len(heights), heights[-1]))
    f.write("static const struct { uint32_t height; UInt256 prevHeader; UInt256 filterHash; }\n")
    f.write("    kFoldVectors[] = {\n")
    for h in heights:
        cur = json.loads(rpc("getblockfilter", rpc("getblockhash", str(h)), "basic"))
        prev = json.loads(rpc("getblockfilter", rpc("getblockhash", str(h - 1)), "basic"))
        prev_internal = bytes.fromhex(prev["header"])[::-1]
        filter_hash = dsha(bytes.fromhex(cur["filter"]))
        f.write('    { %8d, uint256("%s"),\n                uint256("%s") },\n'
                % (h, prev_internal.hex(), filter_hash.hex()))
    f.write("};\n")
print("wrote %d vectors to %s" % (len(heights), out), file=sys.stderr)
