#!/usr/bin/env bash
# Regenerate native/.../BRCompactFilterCheckpoints.h — DigiByte mainnet BIP157
# basic-filter-header checkpoints — from an operator-controlled full node with
# blockfilterindex=1.
#
# Each entry pins the cumulative filter-header at a fixed height so the wallet's
# TOFU filter-header chain can be cross-checked against a root of trust (R1 from
# the Neutrino review). The node's getblockfilter RPC returns the header in
# reversed (big-endian display) order; the wallet stores it INTERNAL order, so
# each hex is byte-reversed here (verified against BIP157 dSHA256(filterHash||prev)).
#
# Usage: scripts/gen_cf_checkpoints.sh [ssh_target] [ssh_key] [spacing]
#   defaults: root@digiscope.me  ~/.ssh/DigitalOcean  50000
# Requires: ssh access to the node, python3 locally.
set -euo pipefail

SSH_TARGET="${1:-root@digiscope.me}"
SSH_KEY="${2:-$HOME/.ssh/DigitalOcean}"
SPACING="${3:-50000}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/native/src/main/jni/digibytewallet-core/BRCompactFilterCheckpoints.h"

echo "Pulling filter-headers from $SSH_TARGET (spacing $SPACING)..." >&2
RAW="$(ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$SSH_TARGET" bash -s <<EOF
CLI=/usr/local/bin/digibyte-cli
TIP=\$(\$CLI getblockcount)
LAST=\$(( TIP - TIP % $SPACING ))
for (( h=$SPACING; h<=LAST; h+=$SPACING )); do
  hash=\$(\$CLI getblockhash \$h 2>/dev/null) || continue
  hdr=\$(\$CLI getblockfilter "\$hash" basic 2>/dev/null | grep -oE "[0-9a-f]{64}" | head -1)
  [ -n "\$hdr" ] && echo "\$h \$hdr"
done
EOF
)"

echo "$RAW" | python3 - "$OUT" "$SPACING" <<'PY'
import sys
out, spacing = sys.argv[1], sys.argv[2]
rows=[]
for line in sys.stdin:
    p=line.split()
    if len(p)==2 and p[0].isdigit() and len(p[1])==64:
        rows.append((int(p[0]), bytes.fromhex(p[1])[::-1].hex()))  # internal = reverse(RPC hex)
rows.sort()
with open(out,'w') as f:
    f.write("// AUTO-GENERATED by scripts/gen_cf_checkpoints.sh — DigiByte mainnet BIP157\n")
    f.write("// basic-filter-header checkpoints from an operator node (blockfilterindex=1).\n")
    f.write("// Headers stored in the wallet's INTERNAL byte order (= byte-reversed\n")
    f.write("// getblockfilter RPC hex; verified vs BIP157 dSHA256(filterHash||prevHeader)).\n")
    f.write("// %d checkpoints, %s-block spacing.\n" % (len(rows), spacing))
    f.write("#ifndef BRCompactFilterCheckpoints_h\n#define BRCompactFilterCheckpoints_h\n\n#include \"BRInt.h\"\n\n")
    f.write("typedef struct { uint32_t height; UInt256 filterHeader; } BRCFCheckpoint;\n\n")
    f.write("static const BRCFCheckpoint BRMainNetCFCheckpoints[] = {\n")
    for h,internal in rows:
        f.write('    { %8d, uint256("%s") },\n' % (h, internal))
    f.write("};\n\n")
    f.write("static const size_t BRMainNetCFCheckpointsCount = sizeof(BRMainNetCFCheckpoints)/sizeof(BRMainNetCFCheckpoints[0]);\n\n")
    f.write("#endif // BRCompactFilterCheckpoints_h\n")
print("wrote %d checkpoints to %s" % (len(rows), out), file=sys.stderr)
PY
